### ISSUE TITLE
QC destroying variables

### ISSUE THREAD

**Issue by timcadman** [lifecycle-project/ds-upload#94]
The following variables are getting QCd out of the core non_rep: lden_preg, ln_preg, pm10_preg, nox_preg

The following variables are getting QCd out of the yearly rep: lden_, ln_, pm10_, nox_

**Comment by timcadman** [comment]
Some more that are being excluded from core_trimester:

areases_quint_t        
green_dist_t                
greenyn300_t                
green_size_t                
ndvi300_t                   
ndvi500_t                   
ndvi100_t

**Comment by timcadman** [comment]
pm10cu_preg           
pm10fe_preg           
pm10k_preg            
pm10ni_preg           
pm10si_preg           
pm10s_preg            
pm10v_preg            
pm10zn_preg           
pm10_preg             
pm25abs_preg          
pm25cu_preg           
pm25fe_preg           
pm25k_preg            
pm25ni_preg           
pm25si_preg           
pm25s_preg            
pm25v_preg            
pm25zn_preg           
pmcoarse_preg         
trafload100_preg      
trafnear_preg

**Comment by timcadman** [comment]
So another related issue. Some people have requested additional variables to be harmonised (e.g. on eating disorder in WP6). We need to find a way that these get incorporated into all of your dictionaries. At the moment they are missing, and I'm not sure how many other additional variables have also been missed out these dictionaries.

**Comment by timcadman** [comment]
core non_rep: folic_prepreg

**Comment by sidohaakma** [comment]
Added missing variables logging. They where deleted because of all missing.
